"""empty message

Revision ID: 129bb2453fce
Revises: 1bd942e3cdfc
Create Date: 2015-04-23 23:34:51.015472

"""

# revision identifiers, used by Alembic.
revision = '129bb2453fce'
down_revision = '1bd942e3cdfc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
