"""empty message

Revision ID: 1a2dde141725
Revises: 26d1aaee56e
Create Date: 2015-07-17 17:09:18.338553

"""

# revision identifiers, used by Alembic.
revision = '1a2dde141725'
down_revision = '26d1aaee56e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_date', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_date')
    ### end Alembic commands ###
