"""empty message

Revision ID: 1b6b41dc7b83
Revises: 4bcd18db7e43
Create Date: 2015-04-24 11:53:00.715335

"""

# revision identifiers, used by Alembic.
revision = '1b6b41dc7b83'
down_revision = '4bcd18db7e43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    ### end Alembic commands ###
