"""empty message

Revision ID: 1bd942e3cdfc
Revises: 281944167ae0
Create Date: 2015-04-23 23:24:20.241548

"""

# revision identifiers, used by Alembic.
revision = '1bd942e3cdfc'
down_revision = '281944167ae0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
