"""empty message

Revision ID: 1ec3b94ac693
Revises: 2f29c995cc57
Create Date: 2015-07-18 12:42:31.919342

"""

# revision identifiers, used by Alembic.
revision = '1ec3b94ac693'
down_revision = '2f29c995cc57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_oauth_user', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_oauth_user')
    ### end Alembic commands ###
