"""empty message

Revision ID: 2f29c995cc57
Revises: 47987d7ef59f
Create Date: 2015-07-17 17:28:52.169457

"""

# revision identifiers, used by Alembic.
revision = '2f29c995cc57'
down_revision = '47987d7ef59f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True))
    op.drop_column('users', 'join_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('users', 'created_on')
    ### end Alembic commands ###
