"""empty message

Revision ID: 30d908a859a6
Revises: 56e01e281776
Create Date: 2015-05-02 15:33:31.873969

"""

# revision identifiers, used by Alembic.
revision = '30d908a859a6'
down_revision = '56e01e281776'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_email', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_email')
    ### end Alembic commands ###
