"""empty message

Revision ID: 33bf2b6ce201
Revises: None
Create Date: 2015-04-23 22:15:52.522127

"""

# revision identifiers, used by Alembic.
revision = '33bf2b6ce201'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    ### end Alembic commands ###
