"""empty message

Revision ID: 3c6ee72a28a4
Revises: 1a2dde141725
Create Date: 2015-07-17 17:12:04.505552

"""

# revision identifiers, used by Alembic.
revision = '3c6ee72a28a4'
down_revision = '1a2dde141725'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
