"""empty message

Revision ID: 47987d7ef59f
Revises: 8002c2712f8
Create Date: 2015-07-17 17:21:39.760562

"""

# revision identifiers, used by Alembic.
revision = '47987d7ef59f'
down_revision = '8002c2712f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
