"""empty message

Revision ID: 4bcd18db7e43
Revises: 5746d8e205d1
Create Date: 2015-04-23 23:37:58.436256

"""

# revision identifiers, used by Alembic.
revision = '4bcd18db7e43'
down_revision = '5746d8e205d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passhash', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passhash')
    ### end Alembic commands ###
