"""empty message

Revision ID: 4d5f97d3543e
Revises: 2a97a3172686
Create Date: 2015-08-19 16:13:18.724264

"""

# revision identifiers, used by Alembic.
revision = '4d5f97d3543e'
down_revision = '2a97a3172686'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True))
    op.drop_column('users', 'passhash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passhash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###
