"""empty message

Revision ID: 4f195d199f14
Revises: 1b6b41dc7b83
Create Date: 2015-04-25 14:56:19.671092

"""

# revision identifiers, used by Alembic.
revision = '4f195d199f14'
down_revision = '1b6b41dc7b83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    ### end Alembic commands ###
