"""empty message

Revision ID: 56e01e281776
Revises: 4f195d199f14
Create Date: 2015-04-26 01:46:37.310288

"""

# revision identifiers, used by Alembic.
revision = '56e01e281776'
down_revision = '4f195d199f14'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
