"""empty message

Revision ID: 5746d8e205d1
Revises: 129bb2453fce
Create Date: 2015-04-23 23:37:16.302189

"""

# revision identifiers, used by Alembic.
revision = '5746d8e205d1'
down_revision = '129bb2453fce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passhash')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passhash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    ### end Alembic commands ###
