"""empty message

Revision ID: 8002c2712f8
Revises: 3c6ee72a28a4
Create Date: 2015-07-17 17:18:31.275681

"""

# revision identifiers, used by Alembic.
revision = '8002c2712f8'
down_revision = '3c6ee72a28a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
