"""empty message

Revision ID: d60cd7fc681
Revises: 4d5f97d3543e
Create Date: 2015-08-19 17:15:01.621889

"""

# revision identifiers, used by Alembic.
revision = 'd60cd7fc681'
down_revision = '4d5f97d3543e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
